# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c583284a-bd30-4a5a-b918-ee3e4e16f546";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/88ED-06AD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.graphics.enable = true;
  hardware.graphics.extraPackages = with pkgs; [
    rocmPackages.clr
    rocmPackages.hipblas
  ];
  hardware.bluetooth.enable = true;
  
  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "jp";
    variant = "";
  };

  services.udev.extraHwdb = ''
    # Input device ID: bus 0x11 vendor 0x1 product 0x1 Only
    evdev:input:b0011v0001p0001*
      KEYBOARD_KEY_3a=leftctrl
      KEYBOARD_KEY_1d=capslock
      KEYBOARD_KEY_38=muhenkan
      KEYBOARD_KEY_b8=henkan
      KEYBOARD_KEY_9d=ro
      KEYBOARD_KEY_29=yen
      KEYBOARD_KEY_db=leftalt
  '';

  services.fprintd.enable = true;
  nixpkgs.overlays = [
    (final: prev: {
      libfprint = prev.libfprint.overrideAttrs (oldAttrs: {
        version = "git";
        src = final.fetchFromGitHub {
          owner = "archeYR";
          repo = "libfprint-CS9711";
          rev = "02b285c9703c38d308fbe47a3c566ef1e7f883ca";
          sha256 = "sha256-QGrBNqbRNqLZIURI66xkenlQamNW+DQU4WS+CLN4zM8=";
        };
        preConfigure = ''
          if [ -f "libfprint/sigfm/meson.build" ]; then
            sed -i '11,/)/d' libfprint/sigfm/meson.build
          fi
        '';
        buildInputs = oldAttrs.buildInputs ++ [
          final.nss
          final.pixman
        ];
        nativeBuildInputs = oldAttrs.nativeBuildInputs ++ [
          final.opencv
          final.cmake
          final.doctest
          final.pkg-config
        ];
      });
    })
  ];
}
